// Tests for the static agent-discovery files generated by
// scripts/generate-agent-files.js + scripts/generate-agent-skills.js +
// scripts/generate-docs.js. Pins the orank-relevant shape of each
// surface so a refactor can't silently regress.

import { describe, it, expect, beforeAll } from "vitest";
import { execSync } from "child_process";
import { readFileSync, existsSync } from "fs";
import { createHash } from "crypto";

beforeAll(() => {
  if (!existsSync("public/episodes.json")) {
    execSync("node scripts/yaml-to-json.js", { stdio: "pipe" });
  }
  execSync(
    [
      "node scripts/generate-llms.js",
      "node scripts/generate-agent-files.js",
      "node scripts/generate-agent-skills.js",
      "node scripts/generate-docs.js",
      "node scripts/generate-pricing.js",
      "node scripts/generate-auth.js",
    ].join(" && "),
    { stdio: "pipe" }
  );
});

function readJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}
function read(path) {
  return readFileSync(path, "utf8");
}

describe("/.well-known/agent.json", () => {
  let m;
  beforeAll(() => {
    m = readJson("public/.well-known/agent.json");
  });

  it("declares schemaVersion + contentType", () => {
    expect(m.schemaVersion).toBe("1.0");
    expect(m.contentType).toBe("podcast");
  });

  it("lists capabilities including search + transcripts + RSS", () => {
    expect(m.capabilities).toEqual(
      expect.arrayContaining([
        "browse_episodes",
        "search_transcripts",
        "get_latest_episode",
        "subscribe_via_rss",
      ])
    );
  });

  it("publishes endpoint inventory (search, ask, mcp, openapi, agentCard)", () => {
    expect(m.endpoints.search).toMatch(/\/api\/search/);
    expect(m.endpoints.ask).toMatch(/\/ask$/);
    expect(m.endpoints.mcp).toMatch(/\/mcp$/);
    expect(m.endpoints.openapi).toMatch(/\/openapi\.json$/);
    expect(m.endpoints.agentCard).toMatch(/agent-card\.json$/);
  });

  it("lists rateLimits and errorEnvelope blocks (orank Identity check)", () => {
    expect(m.rateLimits.perMinute).toBe(60);
    expect(m.rateLimits.headers).toContain("X-RateLimit-Remaining");
    expect(m.errorEnvelope.statusCodes).toEqual(
      expect.arrayContaining([400, 404, 429, 500])
    );
  });

  it("publishes WorkOS auth.md agent_auth block + auth.md surface URIs", () => {
    expect(m.agent_auth).toBeTruthy();
    expect(m.agent_auth.register_uri).toMatch(/\/oauth\/register$/);
    expect(m.agent_auth.claim_uri).toMatch(/\/oauth\/claim$/);
    expect(m.agent_auth.revocation_uri).toMatch(/\/oauth\/revoke$/);
    expect(m.agent_auth.identity_types_supported).toEqual(
      expect.arrayContaining(["anonymous", "client_credentials", "identity_assertion"])
    );
    expect(m.agent_auth.id_jag_supported).toBe(true);
    expect(m.agent_auth.auth_md).toMatch(/\/auth\.md$/);
    expect(m.endpoints.authMd).toMatch(/\/auth\.md$/);
    expect(m.endpoints.agentAuthChallenge).toMatch(/\/agent\/auth$/);
    expect(m.endpoints.oauthClaim).toMatch(/\/oauth\/claim$/);
    expect(m.endpoints.oauthRevoke).toMatch(/\/oauth\/revoke$/);
  });
});

describe("/auth.md (WorkOS auth.md spec)", () => {
  let md;
  beforeAll(() => {
    md = read("public/auth.md");
  });

  it("leads with a top-level heading and has substantial prose", () => {
    expect(md.split("\n")[0]).toMatch(/^# /);
    expect(md.length).toBeGreaterThan(200);
  });

  it("includes all seven WorkOS spec sections", () => {
    for (const heading of ["Discover", "Pick a method", "Register", "Claim", "Use the credential", "Errors", "Revocation"]) {
      expect(md).toContain(`## ${heading}`);
    }
  });

  it("includes spec anchor keywords (agent_auth, register_uri, identity_assertion, id-jag, WWW-Authenticate)", () => {
    expect(md).toContain("agent_auth");
    expect(md).toContain("register_uri");
    expect(md).toContain("identity_assertion");
    expect(md).toMatch(/id-?jag/i);
    expect(md).toContain("WWW-Authenticate");
  });

  it("references the three agent_auth URIs and the JWKS endpoint", () => {
    expect(md).toContain("/oauth/register");
    expect(md).toContain("/oauth/claim");
    expect(md).toContain("/oauth/revoke");
    expect(md).toContain("/oauth/jwks.json");
  });
});

describe("/.well-known/agent-card.json (A2A)", () => {
  let card;
  beforeAll(() => {
    card = readJson("public/.well-known/agent-card.json");
  });

  it("declares protocolVersion + skills array", () => {
    expect(card.protocolVersion).toBe("0.2");
    expect(Array.isArray(card.skills)).toBe(true);
    expect(card.skills.length).toBeGreaterThanOrEqual(5);
  });

  it("each skill has id + name + description + tags", () => {
    for (const s of card.skills) {
      expect(s.id).toBeTruthy();
      expect(s.name).toBeTruthy();
      expect(s.description.length).toBeGreaterThan(20);
      expect(Array.isArray(s.tags)).toBe(true);
    }
  });
});

describe("/.well-known/agent-skills/index.json (agentskills.io v0.2.0)", () => {
  let idx;
  beforeAll(() => {
    idx = readJson("public/.well-known/agent-skills/index.json");
  });

  it("declares the v0.2.0 schema URL", () => {
    expect(idx.$schema).toMatch(/\/discovery\/0\.2\.0\/schema\.json$/);
    expect(idx.version).toBe("0.2.0");
  });

  it("includes top-level instructions/whenToUse (orank Identity check)", () => {
    expect(idx.instructions).toBeTruthy();
    expect(idx.whenToUse).toBeTruthy();
  });

  it("each skill carries whenToUse + sha256 digest", () => {
    expect(idx.skills.length).toBeGreaterThanOrEqual(6);
    for (const s of idx.skills) {
      expect(s.whenToUse).toBeTruthy();
      expect(s.digest).toMatch(/^sha256:[0-9a-f]{64}$/);
      expect(s.type).toBe("skill-md");
    }
  });

  it("digests match the actual SKILL.md byte content", () => {
    for (const s of idx.skills) {
      const path = `public/.well-known/agent-skills/${s.name}/SKILL.md`;
      const md = read(path);
      const expected = "sha256:" + createHash("sha256").update(md, "utf8").digest("hex");
      expect(s.digest).toBe(expected);
    }
  });
});

describe("Per-skill SKILL.md frontmatter", () => {
  let idx;
  beforeAll(() => {
    idx = readJson("public/.well-known/agent-skills/index.json");
  });

  it("each SKILL.md has when_to_use + metadata frontmatter and a When-to-use body section", () => {
    for (const s of idx.skills) {
      const md = read(`public/.well-known/agent-skills/${s.name}/SKILL.md`);
      expect(md).toMatch(/^---/);
      expect(md).toMatch(/^name: /m);
      expect(md).toMatch(/^description: /m);
      expect(md).toMatch(/^when_to_use: /m);
      expect(md).toMatch(/## When to use/);
      expect(md).toMatch(/## How to use/);
    }
  });
});

describe("/SKILL.md (skills.sh root manifest)", () => {
  let md;
  beforeAll(() => {
    md = read("public/SKILL.md");
  });

  it("opens with frontmatter (name, description, when_to_use, metadata)", () => {
    expect(md).toMatch(/^---/);
    expect(md).toMatch(/^name: /m);
    expect(md).toMatch(/^description: /m);
    expect(md).toMatch(/^when_to_use: /m);
    expect(md).toMatch(/^metadata:/m);
  });

  it("lists all six listener skills", () => {
    expect(md).toMatch(/find-episode-by-topic/);
    expect(md).toMatch(/search-transcripts/);
    expect(md).toMatch(/get-latest-episode/);
    expect(md).toMatch(/list-episodes/);
    expect(md).toMatch(/subscribe-via-rss/);
    expect(md).toMatch(/get-episode/);
  });

  it("documents the OAuth + scopes + rate-limits surface", () => {
    expect(md).toMatch(/## Auth/);
    expect(md).toMatch(/PKCE S256/);
    expect(md).toMatch(/read:episodes/);
    expect(md).toMatch(/## Rate limits/);
  });

  it("includes an `npx skills add` registration hint", () => {
    expect(md).toMatch(/npx skills add/);
  });
});

describe("/AGENTS.md (listener-facing)", () => {
  let md;
  beforeAll(() => {
    md = read("public/AGENTS.md");
  });

  it("includes a cheapest-path-per-capability table", () => {
    expect(md).toMatch(/Cheapest path per capability/);
    expect(md).toMatch(/\| Listener intent \| Endpoint \|/);
  });

  it("documents Auth (optional) + Optional payment / tip jar", () => {
    expect(md).toMatch(/## Authentication \(optional\)/);
    expect(md).toMatch(/PKCE S256/);
    expect(md).toMatch(/## Optional payment \/ tip jar/);
    expect(md).toMatch(/HTTP 402/);
  });

  it("links every section-level llms.txt + the /llms-full.txt aggregate", () => {
    expect(md).toContain("/llms.txt");
    expect(md).toContain("/episodes/llms.txt");
    expect(md).toContain("/api/llms.txt");
    expect(md).toContain("/docs/llms.txt");
    expect(md).toContain("/.well-known/llms.txt");
    expect(md).toContain("/llms-full.txt");
  });

  it("links the OAuth + x402 discovery surfaces", () => {
    expect(md).toContain("/.well-known/oauth-authorization-server");
    expect(md).toContain("/.well-known/oauth-protected-resource");
    expect(md).toContain("/.well-known/openid-configuration");
    expect(md).toContain("/.well-known/x402/supported");
  });
});

describe("/docs.md (developer-facing)", () => {
  let md;
  beforeAll(() => {
    md = read("public/docs.md");
  });

  it("includes Quickstart + Authentication + SDK install", () => {
    expect(md).toMatch(/## Quickstart/);
    expect(md).toMatch(/## Authentication/);
    expect(md).toMatch(/## SDK install/);
  });

  it("walks through both client_credentials and authorization_code + PKCE flows", () => {
    expect(md).toMatch(/client_credentials/);
    expect(md).toMatch(/authorization_code/);
    expect(md).toMatch(/code_challenge/);
  });

  it("documents the scope table", () => {
    expect(md).toMatch(/read:episodes/);
    expect(md).toMatch(/read:transcripts/);
    expect(md).toMatch(/search:episodes/);
  });

  it("documents the optional x402 / MPP tip jar with a curl example", () => {
    expect(md).toMatch(/## Optional: tip jar \(x402 \/ MPP\)/);
    expect(md).toMatch(/HTTP\/1\.1 402/);
  });

  it("declares 402 in the error code table", () => {
    const errSection = md.split("## Errors")[1] || "";
    expect(errSection).toMatch(/\| 402 \|/);
  });
});

describe("/.well-known/schema-map.xml (NLWeb)", () => {
  let xml;
  beforeAll(() => {
    xml = read("public/.well-known/schema-map.xml");
  });

  it("emits a schemamap envelope with multiple feeds", () => {
    expect(xml).toMatch(/<\?xml/);
    expect(xml).toMatch(/<schemamap>/);
    expect(xml).toMatch(/<feed url="[^"]+\/rss\.xml"/);
    expect(xml).toMatch(/<feed url="[^"]+\/episodes\.json"/);
    expect(xml).toMatch(/<feed url="[^"]+\/llms\.txt"/);
    expect(xml).toMatch(/<feed url="[^"]+\/index\.md"/);
  });
});

describe("/.well-known/api-catalog (RFC 9727)", () => {
  let m;
  beforeAll(() => {
    m = readJson("public/.well-known/api-catalog");
  });

  it("declares a linkset with anchored API entries", () => {
    expect(Array.isArray(m.linkset)).toBe(true);
    const anchors = m.linkset.map((l) => l.anchor);
    expect(anchors.some((a) => a.endsWith("/api/search"))).toBe(true);
    expect(anchors.some((a) => a.endsWith("/mcp"))).toBe(true);
    expect(anchors.some((a) => a.endsWith("/ask"))).toBe(true);
  });

  it("each entry's service-desc points at a machine-readable description", () => {
    // service-desc may target OpenAPI, an MCP server-card, or an
    // agent.json capability declaration — all are valid per RFC 9727.
    const allowed = /openapi\.json|server-card\.json|agent\.json|agent-card\.json|auth\.md/;
    for (const entry of m.linkset) {
      if (entry["service-desc"]) {
        expect(entry["service-desc"][0].href).toMatch(allowed);
      }
    }
  });
});

describe("/.well-known/ai-plugin.json (OpenAI plugin manifest)", () => {
  let m;
  beforeAll(() => {
    m = readJson("public/.well-known/ai-plugin.json");
  });

  it("declares schema_version + name_for_model + auth=none", () => {
    expect(m.schema_version).toBe("v1");
    expect(m.name_for_model).toBeTruthy();
    expect(m.auth.type).toBe("none");
  });

  it("points at the OpenAPI spec", () => {
    expect(m.api.url).toMatch(/openapi\.json$/);
  });
});
