// Snapshot-style tests for the static .well-known files generated by
// scripts/generate-oauth.js + scripts/generate-sitemap.js. These are
// the discovery surfaces orank probes for OAuth + tier differentiation
// + DeepSeekBot — the build pipeline must keep their shape stable.

import { describe, it, expect, beforeAll } from "vitest";
import { execSync } from "child_process";
import { readFileSync, existsSync } from "fs";
import config from "../../scripts/load-config.js";

beforeAll(() => {
  // Ensure the generators have run at least once. They're idempotent and
  // fast — running them in beforeAll shields the tests from a stale
  // dist/ checkout.
  execSync("node scripts/yaml-to-json.js && node scripts/generate-sitemap.js && node scripts/generate-oauth.js", {
    stdio: "pipe",
  });
});

const SITE = "{{SITE_URL}}";
const SCOPES = ["read:episodes", "read:transcripts", "search:episodes"];

function readJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

describe(".well-known/oauth-authorization-server (RFC 8414)", () => {
  let m;
  beforeAll(() => {
    m = readJson("public/.well-known/oauth-authorization-server");
  });

  it("declares issuer + endpoints", () => {
    expect(m.issuer).toBe(SITE);
    expect(m.authorization_endpoint).toBe(`${SITE}/oauth/authorize`);
    expect(m.token_endpoint).toBe(`${SITE}/oauth/token`);
    expect(m.registration_endpoint).toBe(`${SITE}/oauth/register`);
    expect(m.jwks_uri).toBe(`${SITE}/oauth/jwks.json`);
  });

  it("declares S256 code_challenge support", () => {
    expect(m.code_challenge_methods_supported).toContain("S256");
  });

  it("declares public-client auth (no client secret)", () => {
    expect(m.token_endpoint_auth_methods_supported).toEqual(["none"]);
  });

  it("publishes the read scopes", () => {
    for (const s of SCOPES) expect(m.scopes_supported).toContain(s);
  });

  it("supports authorization_code, client_credentials, refresh_token", () => {
    expect(m.grant_types_supported).toEqual(
      expect.arrayContaining(["authorization_code", "client_credentials", "refresh_token"])
    );
  });

  it("advertises the revocation_endpoint (RFC 7009)", () => {
    expect(m.revocation_endpoint).toBe(`${SITE}/oauth/revoke`);
  });

  it("includes jwt-bearer grant for id-jag identity assertions", () => {
    expect(m.grant_types_supported).toContain(
      "urn:ietf:params:oauth:grant-type:jwt-bearer"
    );
  });

  it("publishes WorkOS auth.md agent_auth block", () => {
    expect(m.agent_auth).toBeTruthy();
    expect(m.agent_auth.register_uri).toBe(`${SITE}/oauth/register`);
    expect(m.agent_auth.claim_uri).toBe(`${SITE}/oauth/claim`);
    expect(m.agent_auth.revocation_uri).toBe(`${SITE}/oauth/revoke`);
    expect(m.agent_auth.identity_types_supported).toEqual(
      expect.arrayContaining(["anonymous", "client_credentials", "identity_assertion"])
    );
    expect(m.agent_auth.identity_assertion_supported).toBe(true);
    expect(m.agent_auth.id_jag_supported).toBe(true);
    expect(m.agent_auth.auth_md).toBe(`${SITE}/auth.md`);
  });

  it("agent_auth.skill back-points at the use-agent-auth SKILL.md", () => {
    expect(m.agent_auth.skill).toBe(
      `${SITE}/.well-known/agent-skills/use-agent-auth/SKILL.md`
    );
    expect(Array.isArray(m.agent_auth.skills)).toBe(true);
    expect(m.agent_auth.skills[0].name).toBe("use-agent-auth");
  });

  it("publishes registration_templates with anonymous + user-email-app + service-account", () => {
    expect(Array.isArray(m.agent_auth.registration_templates)).toBe(true);
    const ids = m.agent_auth.registration_templates.map((t) => t.id);
    expect(ids).toEqual(
      expect.arrayContaining([
        "anonymous-public-client",
        "user-email-app",
        "service-account",
      ])
    );
    expect(m.registration_endpoint_methods_supported).toEqual(
      expect.arrayContaining(["GET", "POST"])
    );
    expect(m.registration_templates_uri).toBe(`${SITE}/oauth/register`);
  });

  it("user-email-app template marks user_email as required + identity_type=identity_assertion", () => {
    const email = m.agent_auth.registration_templates.find(
      (t) => t.id === "user-email-app",
    );
    expect(email.identity_type).toBe("identity_assertion");
    expect(email.required_fields).toContain("user_email");
    expect(email.request_body_template.user_email).toBe("{{user_email}}");
  });

  it("agent_auth.steps walks Discover → Register → Claim → Use → Revoke", () => {
    expect(Array.isArray(m.agent_auth.steps)).toBe(true);
    expect(m.agent_auth.steps).toHaveLength(5);
    expect(m.agent_auth.steps.map((s) => s.name)).toEqual([
      "Discover",
      "Register",
      "Claim",
      "Use",
      "Revoke",
    ]);
  });

  it("publishes top-level auth_md + agent_documentation pointers", () => {
    expect(m.auth_md).toBe(`${SITE}/auth.md`);
    expect(m.agent_documentation).toBe(`${SITE}/auth.md`);
    expect(m.agent_documentation_uri).toBe(`${SITE}/auth.md`);
  });
});

describe(".well-known/oauth-protected-resource (RFC 9728)", () => {
  let m;
  beforeAll(() => {
    m = readJson("public/.well-known/oauth-protected-resource");
  });

  it("references the authorization server", () => {
    expect(m.resource).toBe(SITE);
    expect(m.authorization_servers).toContain(SITE);
  });

  it("publishes the read scopes", () => {
    for (const s of SCOPES) expect(m.scopes_supported).toContain(s);
  });

  it("declares bearer-header auth method", () => {
    expect(m.bearer_methods_supported).toContain("header");
  });

  it("flags auth as optional via x-auth-required: false", () => {
    expect(m["x-auth-required"]).toBe(false);
    expect(m["x-auth-modes"]).toEqual(expect.arrayContaining(["anonymous", "bearer"]));
  });

  it("cross-links to AS metadata + agent_auth block", () => {
    expect(m.authorization_server_metadata).toBe(
      `${SITE}/.well-known/oauth-authorization-server`
    );
    expect(m.agent_auth).toBeTruthy();
    expect(m.agent_auth.register_uri).toBe(`${SITE}/oauth/register`);
    expect(m.agent_auth.claim_uri).toBe(`${SITE}/oauth/claim`);
    expect(m.agent_auth.revocation_uri).toBe(`${SITE}/oauth/revoke`);
    expect(m.auth_md).toBe(`${SITE}/auth.md`);
  });

  it("PRM agent_auth carries the same skill back-pointer as AS", () => {
    expect(m.agent_auth.skill).toBe(
      `${SITE}/.well-known/agent-skills/use-agent-auth/SKILL.md`
    );
  });
});

describe(".well-known/openid-configuration", () => {
  let m;
  beforeAll(() => {
    m = readJson("public/.well-known/openid-configuration");
  });

  it("includes openid in scopes alongside the read scopes", () => {
    expect(m.scopes_supported).toContain("openid");
    for (const s of SCOPES) expect(m.scopes_supported).toContain(s);
  });

  it("publishes a userinfo endpoint", () => {
    expect(m.userinfo_endpoint).toBe(`${SITE}/oauth/userinfo`);
  });

  it("declares EdDSA + HS256 id_token signing", () => {
    expect(m.id_token_signing_alg_values_supported).toContain("EdDSA");
    expect(m.id_token_signing_alg_values_supported).toContain("HS256");
  });
});

describe(".well-known/x402 + discovery", () => {
  it("x402/supported declares the Base Sepolia USDC contract (v2 wire format)", () => {
    const m = readJson("public/.well-known/x402/supported");
    expect(m.x402Version).toBe(2);
    // v2: network is a CAIP-2 chain id; the human label rides in extra.
    expect(m.network).toBe("eip155:84532");
    expect(m.accepts[0].asset).toMatch(/^0x[a-fA-F0-9]{40}$/);
    expect(m.accepts[0].extra?.name).toBe("USDC");
    expect(m.accepts[0].extra?.networkLabel).toBe("base-sepolia");
  });

  it("discovery/resources lists /donate as a resource", () => {
    const m = readJson("public/.well-known/discovery/resources");
    expect(m.resources).toHaveLength(1);
    expect(m.resources[0].resource).toBe(`${SITE}/donate`);
    expect(m.resources[0].methods).toContain("POST");
  });
});

describe("robots.txt", () => {
  let txt;
  beforeAll(() => {
    txt = readFileSync("public/robots.txt", "utf8");
  });

  it("declares Sitemap and Schemamap at the top", () => {
    expect(txt).toMatch(/^Sitemap: \{\{SITE_URL\}\}\/sitemap\.xml$/m);
    expect(txt).toMatch(/^Schemamap: \{\{SITE_URL\}\}\/\.well-known\/schema-map\.xml$/m);
  });

  it("allows runtime answer engines under one grouped rule (Content-Signal: search=yes, ai-input=yes / Allow: /)", () => {
    // forter-style grouped block — all User-agent lines share one
    // Content-Signal + Allow.
    for (const bot of [
      "ChatGPT-User", "OAI-SearchBot", "PerplexityBot", "Perplexity-User",
      "Claude-User", "Claude-SearchBot", "Applebot", "Googlebot",
      "Google-CloudVertexBot", "DuckAssistBot", "Amazonbot",
      "MistralAI-User", "Cohere-AI", "DeepSeekBot",
    ]) {
      expect(txt, `${bot} missing`).toMatch(new RegExp(`^User-agent: ${bot}$`, "m"));
    }
    // The runtime group contains the search=yes, ai-input=yes signal
    // (no ai-train= suffix) followed by Allow: /.
    expect(txt).toMatch(/Content-Signal: search=yes, ai-input=yes\nAllow: \//);
  });

  it("always blocks training-only crawlers (orank robots-ai-policy-quality)", () => {
    // CCBot + Bytespider + Meta + scrapers — Disallow regardless of
    // ai_training. orank awards the point for blocking these.
    for (const bot of [
      "CCBot", "Bytespider", "FacebookBot", "Meta-ExternalAgent",
      "ImagesiftBot", "Diffbot", "omgili", "omgilibot",
    ]) {
      expect(txt, `${bot} missing from blocked group`).toMatch(new RegExp(`^User-agent: ${bot}$`, "m"));
    }
    expect(txt).toMatch(/Content-Signal: search=no, ai-input=no, ai-train=no\nDisallow: \//);
  });

  it("gates mixed training+reasoning crawlers on ai_training", () => {
    const rule = config.ai_training ? "Allow" : "Disallow";
    const train = config.ai_training ? "yes" : "no";
    // GPTBot / ClaudeBot / anthropic-ai / Google-Extended / Applebot-
    // Extended all share the same rule block (grouped).
    for (const bot of ["GPTBot", "ClaudeBot", "anthropic-ai", "Google-Extended", "Applebot-Extended"]) {
      expect(txt, `${bot} missing`).toMatch(new RegExp(`^User-agent: ${bot}$`, "m"));
    }
    expect(txt).toMatch(
      new RegExp(`Content-Signal: search=yes, ai-input=yes, ai-train=${train}\\n${rule}: /`),
    );
  });

  it("emits a generic User-agent: * with Content-Signal (no Crawl-delay)", () => {
    const train = config.ai_training ? "yes" : "no";
    expect(txt).toMatch(
      new RegExp(`User-agent: \\*\\nContent-Signal: search=yes, ai-input=yes, ai-train=${train}\\nAllow: /`),
    );
    expect(txt).not.toMatch(/Crawl-delay/i);
  });

  it("is concise — no more than 60 lines (forter-style grouping)", () => {
    const lines = txt.split("\n").length;
    expect(lines, `robots.txt grew to ${lines} lines — review grouping`).toBeLessThanOrEqual(60);
  });
});

describe("sitemap.xml", () => {
  let xml;
  beforeAll(() => {
    if (!existsSync("public/sitemap.xml")) {
      execSync("node scripts/generate-sitemap.js", { stdio: "pipe" });
    }
    xml = readFileSync("public/sitemap.xml", "utf8");
  });

  it("declares an XML urlset envelope", () => {
    expect(xml).toMatch(/^<\?xml/);
    expect(xml).toMatch(/<urlset xmlns="http:\/\/www\.sitemaps\.org\/schemas\/sitemap\/0\.9">/);
  });

  it("includes the homepage with priority 1.0", () => {
    expect(xml).toMatch(/<loc>\{\{SITE_URL\}\}\/<\/loc>[\s\S]*?<priority>1\.0<\/priority>/);
  });

  it("includes /docs and /pricing aliases", () => {
    expect(xml).toContain("<loc>{{SITE_URL}}/docs</loc>");
    expect(xml).toContain("<loc>{{SITE_URL}}/pricing</loc>");
  });

  it("includes /llms.txt and /llms-full.txt", () => {
    expect(xml).toContain("<loc>{{SITE_URL}}/llms.txt</loc>");
    expect(xml).toContain("<loc>{{SITE_URL}}/llms-full.txt</loc>");
  });
});
