// Snapshot-style tests for the static .well-known files generated by
// scripts/generate-oauth.js + scripts/generate-sitemap.js. These are
// the discovery surfaces orank probes for OAuth + tier differentiation
// + DeepSeekBot — the build pipeline must keep their shape stable.

import { describe, it, expect, beforeAll } from "vitest";
import { execSync } from "child_process";
import { readFileSync, existsSync } from "fs";

beforeAll(() => {
  // Ensure the generators have run at least once. They're idempotent and
  // fast — running them in beforeAll shields the tests from a stale
  // dist/ checkout.
  execSync("node scripts/yaml-to-json.js && node scripts/generate-sitemap.js && node scripts/generate-oauth.js", {
    stdio: "pipe",
  });
});

const SITE = "{{SITE_URL}}";
const SCOPES = ["read:episodes", "read:transcripts", "search:episodes"];

function readJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

describe(".well-known/oauth-authorization-server (RFC 8414)", () => {
  let m;
  beforeAll(() => {
    m = readJson("public/.well-known/oauth-authorization-server");
  });

  it("declares issuer + endpoints", () => {
    expect(m.issuer).toBe(SITE);
    expect(m.authorization_endpoint).toBe(`${SITE}/oauth/authorize`);
    expect(m.token_endpoint).toBe(`${SITE}/oauth/token`);
    expect(m.registration_endpoint).toBe(`${SITE}/oauth/register`);
    expect(m.jwks_uri).toBe(`${SITE}/oauth/jwks.json`);
  });

  it("declares S256 code_challenge support", () => {
    expect(m.code_challenge_methods_supported).toContain("S256");
  });

  it("declares public-client auth (no client secret)", () => {
    expect(m.token_endpoint_auth_methods_supported).toEqual(["none"]);
  });

  it("publishes the read scopes", () => {
    for (const s of SCOPES) expect(m.scopes_supported).toContain(s);
  });

  it("supports authorization_code, client_credentials, refresh_token", () => {
    expect(m.grant_types_supported).toEqual(
      expect.arrayContaining(["authorization_code", "client_credentials", "refresh_token"])
    );
  });
});

describe(".well-known/oauth-protected-resource (RFC 9728)", () => {
  let m;
  beforeAll(() => {
    m = readJson("public/.well-known/oauth-protected-resource");
  });

  it("references the authorization server", () => {
    expect(m.resource).toBe(SITE);
    expect(m.authorization_servers).toContain(SITE);
  });

  it("publishes the read scopes", () => {
    for (const s of SCOPES) expect(m.scopes_supported).toContain(s);
  });

  it("declares bearer-header auth method", () => {
    expect(m.bearer_methods_supported).toContain("header");
  });

  it("flags auth as optional via x-auth-required: false", () => {
    expect(m["x-auth-required"]).toBe(false);
    expect(m["x-auth-modes"]).toEqual(expect.arrayContaining(["anonymous", "bearer"]));
  });
});

describe(".well-known/openid-configuration", () => {
  let m;
  beforeAll(() => {
    m = readJson("public/.well-known/openid-configuration");
  });

  it("includes openid in scopes alongside the read scopes", () => {
    expect(m.scopes_supported).toContain("openid");
    for (const s of SCOPES) expect(m.scopes_supported).toContain(s);
  });

  it("publishes a userinfo endpoint", () => {
    expect(m.userinfo_endpoint).toBe(`${SITE}/oauth/userinfo`);
  });

  it("declares EdDSA + HS256 id_token signing", () => {
    expect(m.id_token_signing_alg_values_supported).toContain("EdDSA");
    expect(m.id_token_signing_alg_values_supported).toContain("HS256");
  });
});

describe(".well-known/x402 + discovery", () => {
  it("x402/supported declares the Base Sepolia USDC contract (v2 wire format)", () => {
    const m = readJson("public/.well-known/x402/supported");
    expect(m.x402Version).toBe(2);
    // v2: network is a CAIP-2 chain id; the human label rides in extra.
    expect(m.network).toBe("eip155:84532");
    expect(m.accepts[0].asset).toMatch(/^0x[a-fA-F0-9]{40}$/);
    expect(m.accepts[0].extra?.name).toBe("USDC");
    expect(m.accepts[0].extra?.networkLabel).toBe("base-sepolia");
  });

  it("discovery/resources lists /donate as a resource", () => {
    const m = readJson("public/.well-known/discovery/resources");
    expect(m.resources).toHaveLength(1);
    expect(m.resources[0].resource).toBe(`${SITE}/donate`);
    expect(m.resources[0].methods).toContain("POST");
  });
});

describe("robots.txt", () => {
  let txt;
  beforeAll(() => {
    txt = readFileSync("public/robots.txt", "utf8");
  });

  it("allows DeepSeekBot in TIER 1", () => {
    expect(txt).toMatch(/User-agent: DeepSeekBot\nContent-Signal:[^\n]+\nAllow: \//);
  });

  it("declares per-bot Content-Signal headers in TIER 1", () => {
    // Every TIER 1 entry has a Content-Signal line above the Allow.
    const tier1 = txt.split("# TIER 2 ")[0];
    const matches = tier1.match(/Content-Signal: search=yes, ai-input=yes(?!, ai-train=)/g) || [];
    expect(matches.length).toBeGreaterThanOrEqual(10);
  });

  it("blocks training crawlers when ai_training=false", () => {
    expect(txt).toMatch(/User-agent: GPTBot\n[^\n]*\nDisallow: \//);
    expect(txt).toMatch(/User-agent: ClaudeBot\n[^\n]*\nDisallow: \//);
    expect(txt).toMatch(/User-agent: CCBot\n[^\n]*\nDisallow: \//);
    expect(txt).toMatch(/User-agent: Bytespider\n[^\n]*\nDisallow: \//);
  });

  it("declares Content-Signal: ai-train=no on TIER 2 blocked bots", () => {
    expect(txt).toMatch(/User-agent: GPTBot\nContent-Signal: search=yes, ai-input=yes, ai-train=no/);
    expect(txt).toMatch(/User-agent: CCBot\nContent-Signal: search=no, ai-input=no, ai-train=no/);
  });

  it("emits global Content-Signal for User-agent: *", () => {
    expect(txt).toMatch(/User-agent: \*\nContent-Signal: search=yes, ai-input=yes, ai-train=no/);
  });

  it("declares Sitemap and Schemamap", () => {
    expect(txt).toMatch(/^Sitemap: \{\{SITE_URL\}\}\/sitemap\.xml$/m);
    expect(txt).toMatch(/^Schemamap: \{\{SITE_URL\}\}\/\.well-known\/schema-map\.xml$/m);
  });

  it("orders TIER 0 → TIER 1 → TIER 2", () => {
    const t0 = txt.indexOf("# TIER 0");
    const t1 = txt.indexOf("# TIER 1");
    const t2 = txt.indexOf("# TIER 2");
    expect(t0).toBeGreaterThanOrEqual(0);
    expect(t1).toBeGreaterThan(t0);
    expect(t2).toBeGreaterThan(t1);
  });
});

describe("sitemap.xml", () => {
  let xml;
  beforeAll(() => {
    if (!existsSync("public/sitemap.xml")) {
      execSync("node scripts/generate-sitemap.js", { stdio: "pipe" });
    }
    xml = readFileSync("public/sitemap.xml", "utf8");
  });

  it("declares an XML urlset envelope", () => {
    expect(xml).toMatch(/^<\?xml/);
    expect(xml).toMatch(/<urlset xmlns="http:\/\/www\.sitemaps\.org\/schemas\/sitemap\/0\.9">/);
  });

  it("includes the homepage with priority 1.0", () => {
    expect(xml).toMatch(/<loc>\{\{SITE_URL\}\}\/<\/loc>[\s\S]*?<priority>1\.0<\/priority>/);
  });

  it("includes /docs and /pricing aliases", () => {
    expect(xml).toContain("<loc>{{SITE_URL}}/docs</loc>");
    expect(xml).toContain("<loc>{{SITE_URL}}/pricing</loc>");
  });

  it("includes /llms.txt and /llms-full.txt", () => {
    expect(xml).toContain("<loc>{{SITE_URL}}/llms.txt</loc>");
    expect(xml).toContain("<loc>{{SITE_URL}}/llms-full.txt</loc>");
  });
});
