#!/usr/bin/env python3
"""Correct SRT subtitle files using Gemini AI.

Two modes:
1. TXT available: Use TXT as source-of-truth to correct SRT text
2. No TXT: Best-effort correction of spelling/grammar using Gemini alone
"""

import argparse
import os
import re
import sys
from pathlib import Path

import yaml
from google import genai

sys.path.insert(0, os.path.dirname(__file__))
from shared import project_root

DEFAULT_GEMINI_MODEL = "gemini-3.1-pro-preview"

MAX_ATTEMPTS = 3

TIMESTAMP_RE = re.compile(
    r"\d{2}:\d{2}:\d{2}[,.]\d{3} --> \d{2}:\d{2}:\d{2}[,.]\d{3}"
)


INSTRUCTION_WITH_TXT = """\
You are a subtitle correction agent. You will receive two files:

SRT file — contains numbered subtitle blocks with timestamps and text. The timestamps and block structure are CORRECT. The text may contain spelling errors, wrong words, or grammar issues.

TXT file — contains the proofread, accurate transcription of the same content. It has NO timestamps.

Your task: Correct the text in each SRT block using the TXT file as your source of truth, while following these 6 strict rules:

1. Never add, remove, merge, or split subtitle blocks. The output must have the exact same number of blocks as the input SRT.
2. Never modify any timestamp or block number. Copy them exactly as-is.
3. For each block, find the corresponding segment in the TXT and replace the SRT text with the correct wording and spelling from the TXT.
4. Preserve the original line breaks within each subtitle block (i.e., if a block had 2 lines, keep it as 2 lines with a similar split point).
5. If a block's text already matches the TXT, leave it unchanged.
6. Output a valid SRT file, nothing else. No commentary, no explanations."""

INSTRUCTION_WITHOUT_TXT = """\
You are a subtitle correction agent. You will receive an SRT file generated by automatic speech recognition.

The timestamps and block structure are CORRECT. The text may contain spelling errors, wrong words, missing punctuation, or grammar issues from the automatic transcription.

Your task: Fix the text as best you can, while following these 6 strict rules:

1. Never add, remove, merge, or split subtitle blocks. The output must have the exact same number of blocks as the input SRT.
2. Never modify any timestamp or block number. Copy them exactly as-is.
3. Fix obvious spelling errors, wrong words, and punctuation. Use your knowledge of the language to infer what was likely said.
4. Preserve the original line breaks within each subtitle block (i.e., if a block had 2 lines, keep it as 2 lines with a similar split point).
5. If a block's text looks correct, leave it unchanged. When in doubt, keep the original.
6. Output a valid SRT file, nothing else. No commentary, no explanations."""


def find_srt_files(episodes_dir, srt_basenames=None):
    """Return list of (srt_path, has_txt) tuples for SRT files to process."""
    episodes_path = Path(episodes_dir)
    if srt_basenames:
        srt_paths = [episodes_path / name for name in srt_basenames]
    else:
        srt_paths = sorted(episodes_path.glob("*.srt"))

    result = []
    for srt_path in srt_paths:
        if not srt_path.is_file():
            print(f"SRT file not found: {srt_path}", file=sys.stderr)
            continue
        txt_path = srt_path.with_suffix(".txt")
        result.append((srt_path, txt_path.is_file()))
    return result


def count_srt_blocks(text):
    """Count SRT blocks by timestamp lines.

    Counting bare-number lines is ambiguous: subtitle *text* can be a bare
    number too (e.g. a 20ms cue whose caption is "25"), inflating the count
    and rejecting valid corrections. Timestamp lines are unambiguous.
    """
    return len(TIMESTAMP_RE.findall(text))


def clean_gemini_output(text):
    """Strip markdown code fences Gemini sometimes wraps around the SRT."""
    text = (text or "").strip()
    if text.startswith("```"):
        text = re.sub(r"^```[^\n]*\n", "", text)
        text = re.sub(r"\n```\s*$", "", text)
        text = text.strip()
    return text + "\n" if text else ""


def restore_timestamps(original, corrected):
    """Splice the original timestamps into the corrected output.

    Gemini is told to copy timestamps verbatim, but on long files it
    occasionally rewrites a few (rounding milliseconds etc.), which would
    fail validation and discard an otherwise good text correction. The
    original timestamps are authoritative, so when the block count matches,
    overwrite the corrected timestamps in order instead of rejecting.
    """
    original_ts = TIMESTAMP_RE.findall(original)
    corrected_ts = TIMESTAMP_RE.findall(corrected)
    if len(original_ts) != len(corrected_ts):
        return corrected
    ts_iter = iter(original_ts)
    return TIMESTAMP_RE.sub(lambda _: next(ts_iter), corrected)


def validate_srt_output(original, corrected):
    """Validate that corrected SRT output looks valid compared to original."""
    if not TIMESTAMP_RE.search(corrected):
        return False, "no SRT timestamp lines found in output"

    original_blocks = count_srt_blocks(original)
    corrected_blocks = count_srt_blocks(corrected)
    if original_blocks != corrected_blocks:
        return False, f"block count mismatch: original={original_blocks}, corrected={corrected_blocks}"

    if TIMESTAMP_RE.findall(original) != TIMESTAMP_RE.findall(corrected):
        return False, "timestamps were modified"

    return True, ""


def load_gemini_model():
    """Read gemini_model from podcast.yaml, falling back to the default."""
    config_path = project_root() / "podcast.yaml"
    if not config_path.exists():
        return DEFAULT_GEMINI_MODEL
    with open(config_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f) or {}
    return config.get("gemini_model") or DEFAULT_GEMINI_MODEL


def fix_srt(client, model, srt_path, has_txt):
    """Fix a single SRT file using Gemini. Returns True on success."""
    srt_content = srt_path.read_text(encoding="utf-8")

    if has_txt:
        txt_path = srt_path.with_suffix(".txt")
        txt_content = txt_path.read_text(encoding="utf-8")
        prompt = f"SRT file:\n{srt_content}\n\nTXT file:\n{txt_content}\n\n{INSTRUCTION_WITH_TXT}"
        mode = "with TXT"
    else:
        prompt = f"SRT file:\n{srt_content}\n\n{INSTRUCTION_WITHOUT_TXT}"
        mode = "best-effort"

    for attempt in range(1, MAX_ATTEMPTS + 1):
        response = client.models.generate_content(
            model=model,
            contents=prompt,
        )

        corrected = clean_gemini_output(response.text)
        restored = restore_timestamps(srt_content, corrected)
        if restored != corrected:
            print(
                f"Note: {srt_path.name} — restored original timestamps in Gemini output",
                file=sys.stderr,
            )
            corrected = restored
        valid, reason = validate_srt_output(srt_content, corrected)
        if valid:
            srt_path.write_text(corrected, encoding="utf-8")
            print(f"{srt_path.name} ({mode})")
            return True

        print(
            f"Warning: {srt_path.name} attempt {attempt}/{MAX_ATTEMPTS} — invalid Gemini output: {reason}",
            file=sys.stderr,
        )

    print(f"Error: giving up on {srt_path.name} after {MAX_ATTEMPTS} attempts; keeping original", file=sys.stderr)
    return False


def main():
    parser = argparse.ArgumentParser(
        description="Correct SRT files using Gemini AI."
    )
    parser.add_argument("episodes_dir", help="Path to episodes directory")
    parser.add_argument(
        "--srt-files",
        nargs="+",
        default=None,
        help="Space-separated SRT basenames to process (e.g., s2e45.srt s2e46.srt)",
    )
    args = parser.parse_args()

    gemini_key = os.environ.get("GEMINI_API_KEY")
    if not gemini_key:
        print("Error: missing required environment variable: GEMINI_API_KEY", file=sys.stderr)
        sys.exit(1)

    client = genai.Client(api_key=gemini_key)
    model = load_gemini_model()
    srt_files = find_srt_files(args.episodes_dir, args.srt_files)

    failures = []
    for srt_path, has_txt in srt_files:
        try:
            if not fix_srt(client, model, srt_path, has_txt):
                failures.append(srt_path.name)
        except Exception as e:
            print(f"Error processing {srt_path.name}: {e}", file=sys.stderr)
            failures.append(srt_path.name)

    if failures:
        sys.exit(f"fix_srt: failed to correct {len(failures)} file(s): {', '.join(failures)}")


if __name__ == "__main__":
    main()
